// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wjudger.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wjudger_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wjudger_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wjudger_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_wjudger_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wjudger_2eproto;
class CompileResult;
struct CompileResultDefaultTypeInternal;
extern CompileResultDefaultTypeInternal _CompileResult_default_instance_;
class ExecuteResult;
struct ExecuteResultDefaultTypeInternal;
extern ExecuteResultDefaultTypeInternal _ExecuteResult_default_instance_;
class JudgeArgs;
struct JudgeArgsDefaultTypeInternal;
extern JudgeArgsDefaultTypeInternal _JudgeArgs_default_instance_;
class JudgeReply;
struct JudgeReplyDefaultTypeInternal;
extern JudgeReplyDefaultTypeInternal _JudgeReply_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CompileResult* Arena::CreateMaybeMessage<::CompileResult>(Arena*);
template<> ::ExecuteResult* Arena::CreateMaybeMessage<::ExecuteResult>(Arena*);
template<> ::JudgeArgs* Arena::CreateMaybeMessage<::JudgeArgs>(Arena*);
template<> ::JudgeReply* Arena::CreateMaybeMessage<::JudgeReply>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum JudgeArgs_Language : int {
  JudgeArgs_Language_C = 0,
  JudgeArgs_Language_CPP = 1,
  JudgeArgs_Language_PASCAL = 2,
  JudgeArgs_Language_JAVA = 3,
  JudgeArgs_Language_PYTHON = 4,
  JudgeArgs_Language_JudgeArgs_Language_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  JudgeArgs_Language_JudgeArgs_Language_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool JudgeArgs_Language_IsValid(int value);
constexpr JudgeArgs_Language JudgeArgs_Language_Language_MIN = JudgeArgs_Language_C;
constexpr JudgeArgs_Language JudgeArgs_Language_Language_MAX = JudgeArgs_Language_PYTHON;
constexpr int JudgeArgs_Language_Language_ARRAYSIZE = JudgeArgs_Language_Language_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* JudgeArgs_Language_descriptor();
template<typename T>
inline const std::string& JudgeArgs_Language_Name(T enum_t_value) {
  static_assert(::std::is_same<T, JudgeArgs_Language>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function JudgeArgs_Language_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    JudgeArgs_Language_descriptor(), enum_t_value);
}
inline bool JudgeArgs_Language_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, JudgeArgs_Language* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<JudgeArgs_Language>(
    JudgeArgs_Language_descriptor(), name, value);
}
enum JudgeReply_ResultType : int {
  JudgeReply_ResultType_COMPILE = 0,
  JudgeReply_ResultType_EXECUTE = 1,
  JudgeReply_ResultType_JudgeReply_ResultType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  JudgeReply_ResultType_JudgeReply_ResultType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool JudgeReply_ResultType_IsValid(int value);
constexpr JudgeReply_ResultType JudgeReply_ResultType_ResultType_MIN = JudgeReply_ResultType_COMPILE;
constexpr JudgeReply_ResultType JudgeReply_ResultType_ResultType_MAX = JudgeReply_ResultType_EXECUTE;
constexpr int JudgeReply_ResultType_ResultType_ARRAYSIZE = JudgeReply_ResultType_ResultType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* JudgeReply_ResultType_descriptor();
template<typename T>
inline const std::string& JudgeReply_ResultType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, JudgeReply_ResultType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function JudgeReply_ResultType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    JudgeReply_ResultType_descriptor(), enum_t_value);
}
inline bool JudgeReply_ResultType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, JudgeReply_ResultType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<JudgeReply_ResultType>(
    JudgeReply_ResultType_descriptor(), name, value);
}
// ===================================================================

class JudgeArgs final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:JudgeArgs) */ {
 public:
  inline JudgeArgs() : JudgeArgs(nullptr) {}
  ~JudgeArgs() override;
  explicit constexpr JudgeArgs(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JudgeArgs(const JudgeArgs& from);
  JudgeArgs(JudgeArgs&& from) noexcept
    : JudgeArgs() {
    *this = ::std::move(from);
  }

  inline JudgeArgs& operator=(const JudgeArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline JudgeArgs& operator=(JudgeArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JudgeArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const JudgeArgs* internal_default_instance() {
    return reinterpret_cast<const JudgeArgs*>(
               &_JudgeArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(JudgeArgs& a, JudgeArgs& b) {
    a.Swap(&b);
  }
  inline void Swap(JudgeArgs* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JudgeArgs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JudgeArgs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JudgeArgs>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JudgeArgs& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const JudgeArgs& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JudgeArgs* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "JudgeArgs";
  }
  protected:
  explicit JudgeArgs(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef JudgeArgs_Language Language;
  static constexpr Language C =
    JudgeArgs_Language_C;
  static constexpr Language CPP =
    JudgeArgs_Language_CPP;
  static constexpr Language PASCAL =
    JudgeArgs_Language_PASCAL;
  static constexpr Language JAVA =
    JudgeArgs_Language_JAVA;
  static constexpr Language PYTHON =
    JudgeArgs_Language_PYTHON;
  static inline bool Language_IsValid(int value) {
    return JudgeArgs_Language_IsValid(value);
  }
  static constexpr Language Language_MIN =
    JudgeArgs_Language_Language_MIN;
  static constexpr Language Language_MAX =
    JudgeArgs_Language_Language_MAX;
  static constexpr int Language_ARRAYSIZE =
    JudgeArgs_Language_Language_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Language_descriptor() {
    return JudgeArgs_Language_descriptor();
  }
  template<typename T>
  static inline const std::string& Language_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Language>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Language_Name.");
    return JudgeArgs_Language_Name(enum_t_value);
  }
  static inline bool Language_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Language* value) {
    return JudgeArgs_Language_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kCodeFieldNumber = 1,
    kTimelimitFieldNumber = 3,
    kLanguageFieldNumber = 2,
    kDataIdFieldNumber = 5,
    kMemorylimitFieldNumber = 4,
  };
  // string code = 1;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // uint64 timelimit = 3;
  void clear_timelimit();
  uint64_t timelimit() const;
  void set_timelimit(uint64_t value);
  private:
  uint64_t _internal_timelimit() const;
  void _internal_set_timelimit(uint64_t value);
  public:

  // .JudgeArgs.Language language = 2;
  void clear_language();
  ::JudgeArgs_Language language() const;
  void set_language(::JudgeArgs_Language value);
  private:
  ::JudgeArgs_Language _internal_language() const;
  void _internal_set_language(::JudgeArgs_Language value);
  public:

  // uint32 dataId = 5;
  void clear_dataid();
  uint32_t dataid() const;
  void set_dataid(uint32_t value);
  private:
  uint32_t _internal_dataid() const;
  void _internal_set_dataid(uint32_t value);
  public:

  // double memorylimit = 4;
  void clear_memorylimit();
  double memorylimit() const;
  void set_memorylimit(double value);
  private:
  double _internal_memorylimit() const;
  void _internal_set_memorylimit(double value);
  public:

  // @@protoc_insertion_point(class_scope:JudgeArgs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
  uint64_t timelimit_;
  int language_;
  uint32_t dataid_;
  double memorylimit_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wjudger_2eproto;
};
// -------------------------------------------------------------------

class JudgeReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:JudgeReply) */ {
 public:
  inline JudgeReply() : JudgeReply(nullptr) {}
  ~JudgeReply() override;
  explicit constexpr JudgeReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JudgeReply(const JudgeReply& from);
  JudgeReply(JudgeReply&& from) noexcept
    : JudgeReply() {
    *this = ::std::move(from);
  }

  inline JudgeReply& operator=(const JudgeReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline JudgeReply& operator=(JudgeReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JudgeReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const JudgeReply* internal_default_instance() {
    return reinterpret_cast<const JudgeReply*>(
               &_JudgeReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(JudgeReply& a, JudgeReply& b) {
    a.Swap(&b);
  }
  inline void Swap(JudgeReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JudgeReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JudgeReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JudgeReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JudgeReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const JudgeReply& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JudgeReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "JudgeReply";
  }
  protected:
  explicit JudgeReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef JudgeReply_ResultType ResultType;
  static constexpr ResultType COMPILE =
    JudgeReply_ResultType_COMPILE;
  static constexpr ResultType EXECUTE =
    JudgeReply_ResultType_EXECUTE;
  static inline bool ResultType_IsValid(int value) {
    return JudgeReply_ResultType_IsValid(value);
  }
  static constexpr ResultType ResultType_MIN =
    JudgeReply_ResultType_ResultType_MIN;
  static constexpr ResultType ResultType_MAX =
    JudgeReply_ResultType_ResultType_MAX;
  static constexpr int ResultType_ARRAYSIZE =
    JudgeReply_ResultType_ResultType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ResultType_descriptor() {
    return JudgeReply_ResultType_descriptor();
  }
  template<typename T>
  static inline const std::string& ResultType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ResultType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ResultType_Name.");
    return JudgeReply_ResultType_Name(enum_t_value);
  }
  static inline bool ResultType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ResultType* value) {
    return JudgeReply_ResultType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kCompileResultFieldNumber = 2,
    kExecuteResultFieldNumber = 3,
    kResultTypeFieldNumber = 1,
  };
  // .CompileResult compileResult = 2;
  bool has_compileresult() const;
  private:
  bool _internal_has_compileresult() const;
  public:
  void clear_compileresult();
  const ::CompileResult& compileresult() const;
  PROTOBUF_NODISCARD ::CompileResult* release_compileresult();
  ::CompileResult* mutable_compileresult();
  void set_allocated_compileresult(::CompileResult* compileresult);
  private:
  const ::CompileResult& _internal_compileresult() const;
  ::CompileResult* _internal_mutable_compileresult();
  public:
  void unsafe_arena_set_allocated_compileresult(
      ::CompileResult* compileresult);
  ::CompileResult* unsafe_arena_release_compileresult();

  // .ExecuteResult executeResult = 3;
  bool has_executeresult() const;
  private:
  bool _internal_has_executeresult() const;
  public:
  void clear_executeresult();
  const ::ExecuteResult& executeresult() const;
  PROTOBUF_NODISCARD ::ExecuteResult* release_executeresult();
  ::ExecuteResult* mutable_executeresult();
  void set_allocated_executeresult(::ExecuteResult* executeresult);
  private:
  const ::ExecuteResult& _internal_executeresult() const;
  ::ExecuteResult* _internal_mutable_executeresult();
  public:
  void unsafe_arena_set_allocated_executeresult(
      ::ExecuteResult* executeresult);
  ::ExecuteResult* unsafe_arena_release_executeresult();

  // .JudgeReply.ResultType resultType = 1;
  void clear_resulttype();
  ::JudgeReply_ResultType resulttype() const;
  void set_resulttype(::JudgeReply_ResultType value);
  private:
  ::JudgeReply_ResultType _internal_resulttype() const;
  void _internal_set_resulttype(::JudgeReply_ResultType value);
  public:

  // @@protoc_insertion_point(class_scope:JudgeReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::CompileResult* compileresult_;
  ::ExecuteResult* executeresult_;
  int resulttype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wjudger_2eproto;
};
// -------------------------------------------------------------------

class CompileResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CompileResult) */ {
 public:
  inline CompileResult() : CompileResult(nullptr) {}
  ~CompileResult() override;
  explicit constexpr CompileResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CompileResult(const CompileResult& from);
  CompileResult(CompileResult&& from) noexcept
    : CompileResult() {
    *this = ::std::move(from);
  }

  inline CompileResult& operator=(const CompileResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompileResult& operator=(CompileResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CompileResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const CompileResult* internal_default_instance() {
    return reinterpret_cast<const CompileResult*>(
               &_CompileResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CompileResult& a, CompileResult& b) {
    a.Swap(&b);
  }
  inline void Swap(CompileResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompileResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CompileResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CompileResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CompileResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const CompileResult& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompileResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CompileResult";
  }
  protected:
  explicit CompileResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTestcasesFieldNumber = 2,
    kCompileErrorFieldNumber = 1,
  };
  // repeated string testcases = 2;
  int testcases_size() const;
  private:
  int _internal_testcases_size() const;
  public:
  void clear_testcases();
  const std::string& testcases(int index) const;
  std::string* mutable_testcases(int index);
  void set_testcases(int index, const std::string& value);
  void set_testcases(int index, std::string&& value);
  void set_testcases(int index, const char* value);
  void set_testcases(int index, const char* value, size_t size);
  std::string* add_testcases();
  void add_testcases(const std::string& value);
  void add_testcases(std::string&& value);
  void add_testcases(const char* value);
  void add_testcases(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& testcases() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_testcases();
  private:
  const std::string& _internal_testcases(int index) const;
  std::string* _internal_add_testcases();
  public:

  // bool compile_error = 1;
  void clear_compile_error();
  bool compile_error() const;
  void set_compile_error(bool value);
  private:
  bool _internal_compile_error() const;
  void _internal_set_compile_error(bool value);
  public:

  // @@protoc_insertion_point(class_scope:CompileResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> testcases_;
  bool compile_error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wjudger_2eproto;
};
// -------------------------------------------------------------------

class ExecuteResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ExecuteResult) */ {
 public:
  inline ExecuteResult() : ExecuteResult(nullptr) {}
  ~ExecuteResult() override;
  explicit constexpr ExecuteResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ExecuteResult(const ExecuteResult& from);
  ExecuteResult(ExecuteResult&& from) noexcept
    : ExecuteResult() {
    *this = ::std::move(from);
  }

  inline ExecuteResult& operator=(const ExecuteResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExecuteResult& operator=(ExecuteResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExecuteResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExecuteResult* internal_default_instance() {
    return reinterpret_cast<const ExecuteResult*>(
               &_ExecuteResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ExecuteResult& a, ExecuteResult& b) {
    a.Swap(&b);
  }
  inline void Swap(ExecuteResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExecuteResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExecuteResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ExecuteResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ExecuteResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ExecuteResult& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExecuteResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ExecuteResult";
  }
  protected:
  explicit ExecuteResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTestcaseFieldNumber = 1,
    kVerdictFieldNumber = 5,
    kMsgFieldNumber = 6,
    kTimeusedFieldNumber = 2,
    kMemoryusedFieldNumber = 3,
    kScoreFieldNumber = 4,
  };
  // string testcase = 1;
  void clear_testcase();
  const std::string& testcase() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_testcase(ArgT0&& arg0, ArgT... args);
  std::string* mutable_testcase();
  PROTOBUF_NODISCARD std::string* release_testcase();
  void set_allocated_testcase(std::string* testcase);
  private:
  const std::string& _internal_testcase() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_testcase(const std::string& value);
  std::string* _internal_mutable_testcase();
  public:

  // string verdict = 5;
  void clear_verdict();
  const std::string& verdict() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_verdict(ArgT0&& arg0, ArgT... args);
  std::string* mutable_verdict();
  PROTOBUF_NODISCARD std::string* release_verdict();
  void set_allocated_verdict(std::string* verdict);
  private:
  const std::string& _internal_verdict() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_verdict(const std::string& value);
  std::string* _internal_mutable_verdict();
  public:

  // string msg = 6;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // uint64 timeused = 2;
  void clear_timeused();
  uint64_t timeused() const;
  void set_timeused(uint64_t value);
  private:
  uint64_t _internal_timeused() const;
  void _internal_set_timeused(uint64_t value);
  public:

  // double memoryused = 3;
  void clear_memoryused();
  double memoryused() const;
  void set_memoryused(double value);
  private:
  double _internal_memoryused() const;
  void _internal_set_memoryused(double value);
  public:

  // uint32 score = 4;
  void clear_score();
  uint32_t score() const;
  void set_score(uint32_t value);
  private:
  uint32_t _internal_score() const;
  void _internal_set_score(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ExecuteResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr testcase_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr verdict_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  uint64_t timeused_;
  double memoryused_;
  uint32_t score_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wjudger_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JudgeArgs

// string code = 1;
inline void JudgeArgs::clear_code() {
  code_.ClearToEmpty();
}
inline const std::string& JudgeArgs::code() const {
  // @@protoc_insertion_point(field_get:JudgeArgs.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void JudgeArgs::set_code(ArgT0&& arg0, ArgT... args) {
 
 code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:JudgeArgs.code)
}
inline std::string* JudgeArgs::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:JudgeArgs.code)
  return _s;
}
inline const std::string& JudgeArgs::_internal_code() const {
  return code_.Get();
}
inline void JudgeArgs::_internal_set_code(const std::string& value) {
  
  code_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* JudgeArgs::_internal_mutable_code() {
  
  return code_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* JudgeArgs::release_code() {
  // @@protoc_insertion_point(field_release:JudgeArgs.code)
  return code_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void JudgeArgs::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    
  } else {
    
  }
  code_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), code,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (code_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    code_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:JudgeArgs.code)
}

// .JudgeArgs.Language language = 2;
inline void JudgeArgs::clear_language() {
  language_ = 0;
}
inline ::JudgeArgs_Language JudgeArgs::_internal_language() const {
  return static_cast< ::JudgeArgs_Language >(language_);
}
inline ::JudgeArgs_Language JudgeArgs::language() const {
  // @@protoc_insertion_point(field_get:JudgeArgs.language)
  return _internal_language();
}
inline void JudgeArgs::_internal_set_language(::JudgeArgs_Language value) {
  
  language_ = value;
}
inline void JudgeArgs::set_language(::JudgeArgs_Language value) {
  _internal_set_language(value);
  // @@protoc_insertion_point(field_set:JudgeArgs.language)
}

// uint64 timelimit = 3;
inline void JudgeArgs::clear_timelimit() {
  timelimit_ = uint64_t{0u};
}
inline uint64_t JudgeArgs::_internal_timelimit() const {
  return timelimit_;
}
inline uint64_t JudgeArgs::timelimit() const {
  // @@protoc_insertion_point(field_get:JudgeArgs.timelimit)
  return _internal_timelimit();
}
inline void JudgeArgs::_internal_set_timelimit(uint64_t value) {
  
  timelimit_ = value;
}
inline void JudgeArgs::set_timelimit(uint64_t value) {
  _internal_set_timelimit(value);
  // @@protoc_insertion_point(field_set:JudgeArgs.timelimit)
}

// double memorylimit = 4;
inline void JudgeArgs::clear_memorylimit() {
  memorylimit_ = 0;
}
inline double JudgeArgs::_internal_memorylimit() const {
  return memorylimit_;
}
inline double JudgeArgs::memorylimit() const {
  // @@protoc_insertion_point(field_get:JudgeArgs.memorylimit)
  return _internal_memorylimit();
}
inline void JudgeArgs::_internal_set_memorylimit(double value) {
  
  memorylimit_ = value;
}
inline void JudgeArgs::set_memorylimit(double value) {
  _internal_set_memorylimit(value);
  // @@protoc_insertion_point(field_set:JudgeArgs.memorylimit)
}

// uint32 dataId = 5;
inline void JudgeArgs::clear_dataid() {
  dataid_ = 0u;
}
inline uint32_t JudgeArgs::_internal_dataid() const {
  return dataid_;
}
inline uint32_t JudgeArgs::dataid() const {
  // @@protoc_insertion_point(field_get:JudgeArgs.dataId)
  return _internal_dataid();
}
inline void JudgeArgs::_internal_set_dataid(uint32_t value) {
  
  dataid_ = value;
}
inline void JudgeArgs::set_dataid(uint32_t value) {
  _internal_set_dataid(value);
  // @@protoc_insertion_point(field_set:JudgeArgs.dataId)
}

// -------------------------------------------------------------------

// JudgeReply

// .JudgeReply.ResultType resultType = 1;
inline void JudgeReply::clear_resulttype() {
  resulttype_ = 0;
}
inline ::JudgeReply_ResultType JudgeReply::_internal_resulttype() const {
  return static_cast< ::JudgeReply_ResultType >(resulttype_);
}
inline ::JudgeReply_ResultType JudgeReply::resulttype() const {
  // @@protoc_insertion_point(field_get:JudgeReply.resultType)
  return _internal_resulttype();
}
inline void JudgeReply::_internal_set_resulttype(::JudgeReply_ResultType value) {
  
  resulttype_ = value;
}
inline void JudgeReply::set_resulttype(::JudgeReply_ResultType value) {
  _internal_set_resulttype(value);
  // @@protoc_insertion_point(field_set:JudgeReply.resultType)
}

// .CompileResult compileResult = 2;
inline bool JudgeReply::_internal_has_compileresult() const {
  return this != internal_default_instance() && compileresult_ != nullptr;
}
inline bool JudgeReply::has_compileresult() const {
  return _internal_has_compileresult();
}
inline void JudgeReply::clear_compileresult() {
  if (GetArenaForAllocation() == nullptr && compileresult_ != nullptr) {
    delete compileresult_;
  }
  compileresult_ = nullptr;
}
inline const ::CompileResult& JudgeReply::_internal_compileresult() const {
  const ::CompileResult* p = compileresult_;
  return p != nullptr ? *p : reinterpret_cast<const ::CompileResult&>(
      ::_CompileResult_default_instance_);
}
inline const ::CompileResult& JudgeReply::compileresult() const {
  // @@protoc_insertion_point(field_get:JudgeReply.compileResult)
  return _internal_compileresult();
}
inline void JudgeReply::unsafe_arena_set_allocated_compileresult(
    ::CompileResult* compileresult) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(compileresult_);
  }
  compileresult_ = compileresult;
  if (compileresult) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:JudgeReply.compileResult)
}
inline ::CompileResult* JudgeReply::release_compileresult() {
  
  ::CompileResult* temp = compileresult_;
  compileresult_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::CompileResult* JudgeReply::unsafe_arena_release_compileresult() {
  // @@protoc_insertion_point(field_release:JudgeReply.compileResult)
  
  ::CompileResult* temp = compileresult_;
  compileresult_ = nullptr;
  return temp;
}
inline ::CompileResult* JudgeReply::_internal_mutable_compileresult() {
  
  if (compileresult_ == nullptr) {
    auto* p = CreateMaybeMessage<::CompileResult>(GetArenaForAllocation());
    compileresult_ = p;
  }
  return compileresult_;
}
inline ::CompileResult* JudgeReply::mutable_compileresult() {
  ::CompileResult* _msg = _internal_mutable_compileresult();
  // @@protoc_insertion_point(field_mutable:JudgeReply.compileResult)
  return _msg;
}
inline void JudgeReply::set_allocated_compileresult(::CompileResult* compileresult) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete compileresult_;
  }
  if (compileresult) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::CompileResult>::GetOwningArena(compileresult);
    if (message_arena != submessage_arena) {
      compileresult = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, compileresult, submessage_arena);
    }
    
  } else {
    
  }
  compileresult_ = compileresult;
  // @@protoc_insertion_point(field_set_allocated:JudgeReply.compileResult)
}

// .ExecuteResult executeResult = 3;
inline bool JudgeReply::_internal_has_executeresult() const {
  return this != internal_default_instance() && executeresult_ != nullptr;
}
inline bool JudgeReply::has_executeresult() const {
  return _internal_has_executeresult();
}
inline void JudgeReply::clear_executeresult() {
  if (GetArenaForAllocation() == nullptr && executeresult_ != nullptr) {
    delete executeresult_;
  }
  executeresult_ = nullptr;
}
inline const ::ExecuteResult& JudgeReply::_internal_executeresult() const {
  const ::ExecuteResult* p = executeresult_;
  return p != nullptr ? *p : reinterpret_cast<const ::ExecuteResult&>(
      ::_ExecuteResult_default_instance_);
}
inline const ::ExecuteResult& JudgeReply::executeresult() const {
  // @@protoc_insertion_point(field_get:JudgeReply.executeResult)
  return _internal_executeresult();
}
inline void JudgeReply::unsafe_arena_set_allocated_executeresult(
    ::ExecuteResult* executeresult) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(executeresult_);
  }
  executeresult_ = executeresult;
  if (executeresult) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:JudgeReply.executeResult)
}
inline ::ExecuteResult* JudgeReply::release_executeresult() {
  
  ::ExecuteResult* temp = executeresult_;
  executeresult_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::ExecuteResult* JudgeReply::unsafe_arena_release_executeresult() {
  // @@protoc_insertion_point(field_release:JudgeReply.executeResult)
  
  ::ExecuteResult* temp = executeresult_;
  executeresult_ = nullptr;
  return temp;
}
inline ::ExecuteResult* JudgeReply::_internal_mutable_executeresult() {
  
  if (executeresult_ == nullptr) {
    auto* p = CreateMaybeMessage<::ExecuteResult>(GetArenaForAllocation());
    executeresult_ = p;
  }
  return executeresult_;
}
inline ::ExecuteResult* JudgeReply::mutable_executeresult() {
  ::ExecuteResult* _msg = _internal_mutable_executeresult();
  // @@protoc_insertion_point(field_mutable:JudgeReply.executeResult)
  return _msg;
}
inline void JudgeReply::set_allocated_executeresult(::ExecuteResult* executeresult) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete executeresult_;
  }
  if (executeresult) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::ExecuteResult>::GetOwningArena(executeresult);
    if (message_arena != submessage_arena) {
      executeresult = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, executeresult, submessage_arena);
    }
    
  } else {
    
  }
  executeresult_ = executeresult;
  // @@protoc_insertion_point(field_set_allocated:JudgeReply.executeResult)
}

// -------------------------------------------------------------------

// CompileResult

// bool compile_error = 1;
inline void CompileResult::clear_compile_error() {
  compile_error_ = false;
}
inline bool CompileResult::_internal_compile_error() const {
  return compile_error_;
}
inline bool CompileResult::compile_error() const {
  // @@protoc_insertion_point(field_get:CompileResult.compile_error)
  return _internal_compile_error();
}
inline void CompileResult::_internal_set_compile_error(bool value) {
  
  compile_error_ = value;
}
inline void CompileResult::set_compile_error(bool value) {
  _internal_set_compile_error(value);
  // @@protoc_insertion_point(field_set:CompileResult.compile_error)
}

// repeated string testcases = 2;
inline int CompileResult::_internal_testcases_size() const {
  return testcases_.size();
}
inline int CompileResult::testcases_size() const {
  return _internal_testcases_size();
}
inline void CompileResult::clear_testcases() {
  testcases_.Clear();
}
inline std::string* CompileResult::add_testcases() {
  std::string* _s = _internal_add_testcases();
  // @@protoc_insertion_point(field_add_mutable:CompileResult.testcases)
  return _s;
}
inline const std::string& CompileResult::_internal_testcases(int index) const {
  return testcases_.Get(index);
}
inline const std::string& CompileResult::testcases(int index) const {
  // @@protoc_insertion_point(field_get:CompileResult.testcases)
  return _internal_testcases(index);
}
inline std::string* CompileResult::mutable_testcases(int index) {
  // @@protoc_insertion_point(field_mutable:CompileResult.testcases)
  return testcases_.Mutable(index);
}
inline void CompileResult::set_testcases(int index, const std::string& value) {
  testcases_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:CompileResult.testcases)
}
inline void CompileResult::set_testcases(int index, std::string&& value) {
  testcases_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:CompileResult.testcases)
}
inline void CompileResult::set_testcases(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  testcases_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:CompileResult.testcases)
}
inline void CompileResult::set_testcases(int index, const char* value, size_t size) {
  testcases_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:CompileResult.testcases)
}
inline std::string* CompileResult::_internal_add_testcases() {
  return testcases_.Add();
}
inline void CompileResult::add_testcases(const std::string& value) {
  testcases_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:CompileResult.testcases)
}
inline void CompileResult::add_testcases(std::string&& value) {
  testcases_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:CompileResult.testcases)
}
inline void CompileResult::add_testcases(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  testcases_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:CompileResult.testcases)
}
inline void CompileResult::add_testcases(const char* value, size_t size) {
  testcases_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:CompileResult.testcases)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
CompileResult::testcases() const {
  // @@protoc_insertion_point(field_list:CompileResult.testcases)
  return testcases_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
CompileResult::mutable_testcases() {
  // @@protoc_insertion_point(field_mutable_list:CompileResult.testcases)
  return &testcases_;
}

// -------------------------------------------------------------------

// ExecuteResult

// string testcase = 1;
inline void ExecuteResult::clear_testcase() {
  testcase_.ClearToEmpty();
}
inline const std::string& ExecuteResult::testcase() const {
  // @@protoc_insertion_point(field_get:ExecuteResult.testcase)
  return _internal_testcase();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteResult::set_testcase(ArgT0&& arg0, ArgT... args) {
 
 testcase_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ExecuteResult.testcase)
}
inline std::string* ExecuteResult::mutable_testcase() {
  std::string* _s = _internal_mutable_testcase();
  // @@protoc_insertion_point(field_mutable:ExecuteResult.testcase)
  return _s;
}
inline const std::string& ExecuteResult::_internal_testcase() const {
  return testcase_.Get();
}
inline void ExecuteResult::_internal_set_testcase(const std::string& value) {
  
  testcase_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ExecuteResult::_internal_mutable_testcase() {
  
  return testcase_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ExecuteResult::release_testcase() {
  // @@protoc_insertion_point(field_release:ExecuteResult.testcase)
  return testcase_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ExecuteResult::set_allocated_testcase(std::string* testcase) {
  if (testcase != nullptr) {
    
  } else {
    
  }
  testcase_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), testcase,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (testcase_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    testcase_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExecuteResult.testcase)
}

// uint64 timeused = 2;
inline void ExecuteResult::clear_timeused() {
  timeused_ = uint64_t{0u};
}
inline uint64_t ExecuteResult::_internal_timeused() const {
  return timeused_;
}
inline uint64_t ExecuteResult::timeused() const {
  // @@protoc_insertion_point(field_get:ExecuteResult.timeused)
  return _internal_timeused();
}
inline void ExecuteResult::_internal_set_timeused(uint64_t value) {
  
  timeused_ = value;
}
inline void ExecuteResult::set_timeused(uint64_t value) {
  _internal_set_timeused(value);
  // @@protoc_insertion_point(field_set:ExecuteResult.timeused)
}

// double memoryused = 3;
inline void ExecuteResult::clear_memoryused() {
  memoryused_ = 0;
}
inline double ExecuteResult::_internal_memoryused() const {
  return memoryused_;
}
inline double ExecuteResult::memoryused() const {
  // @@protoc_insertion_point(field_get:ExecuteResult.memoryused)
  return _internal_memoryused();
}
inline void ExecuteResult::_internal_set_memoryused(double value) {
  
  memoryused_ = value;
}
inline void ExecuteResult::set_memoryused(double value) {
  _internal_set_memoryused(value);
  // @@protoc_insertion_point(field_set:ExecuteResult.memoryused)
}

// uint32 score = 4;
inline void ExecuteResult::clear_score() {
  score_ = 0u;
}
inline uint32_t ExecuteResult::_internal_score() const {
  return score_;
}
inline uint32_t ExecuteResult::score() const {
  // @@protoc_insertion_point(field_get:ExecuteResult.score)
  return _internal_score();
}
inline void ExecuteResult::_internal_set_score(uint32_t value) {
  
  score_ = value;
}
inline void ExecuteResult::set_score(uint32_t value) {
  _internal_set_score(value);
  // @@protoc_insertion_point(field_set:ExecuteResult.score)
}

// string verdict = 5;
inline void ExecuteResult::clear_verdict() {
  verdict_.ClearToEmpty();
}
inline const std::string& ExecuteResult::verdict() const {
  // @@protoc_insertion_point(field_get:ExecuteResult.verdict)
  return _internal_verdict();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteResult::set_verdict(ArgT0&& arg0, ArgT... args) {
 
 verdict_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ExecuteResult.verdict)
}
inline std::string* ExecuteResult::mutable_verdict() {
  std::string* _s = _internal_mutable_verdict();
  // @@protoc_insertion_point(field_mutable:ExecuteResult.verdict)
  return _s;
}
inline const std::string& ExecuteResult::_internal_verdict() const {
  return verdict_.Get();
}
inline void ExecuteResult::_internal_set_verdict(const std::string& value) {
  
  verdict_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ExecuteResult::_internal_mutable_verdict() {
  
  return verdict_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ExecuteResult::release_verdict() {
  // @@protoc_insertion_point(field_release:ExecuteResult.verdict)
  return verdict_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ExecuteResult::set_allocated_verdict(std::string* verdict) {
  if (verdict != nullptr) {
    
  } else {
    
  }
  verdict_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), verdict,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (verdict_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    verdict_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExecuteResult.verdict)
}

// string msg = 6;
inline void ExecuteResult::clear_msg() {
  msg_.ClearToEmpty();
}
inline const std::string& ExecuteResult::msg() const {
  // @@protoc_insertion_point(field_get:ExecuteResult.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExecuteResult::set_msg(ArgT0&& arg0, ArgT... args) {
 
 msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ExecuteResult.msg)
}
inline std::string* ExecuteResult::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:ExecuteResult.msg)
  return _s;
}
inline const std::string& ExecuteResult::_internal_msg() const {
  return msg_.Get();
}
inline void ExecuteResult::_internal_set_msg(const std::string& value) {
  
  msg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* ExecuteResult::_internal_mutable_msg() {
  
  return msg_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* ExecuteResult::release_msg() {
  // @@protoc_insertion_point(field_release:ExecuteResult.msg)
  return msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void ExecuteResult::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (msg_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExecuteResult.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::JudgeArgs_Language> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::JudgeArgs_Language>() {
  return ::JudgeArgs_Language_descriptor();
}
template <> struct is_proto_enum< ::JudgeReply_ResultType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::JudgeReply_ResultType>() {
  return ::JudgeReply_ResultType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wjudger_2eproto
