// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: wjudger.proto
#ifndef GRPC_wjudger_2eproto__INCLUDED
#define GRPC_wjudger_2eproto__INCLUDED

#include "wjudger.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace WJudger {

class WJudger final {
 public:
  static constexpr char const* service_full_name() {
    return "WJudger.WJudger";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::WJudger::JudgeReply>> Judge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::WJudger::JudgeReply>>(JudgeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WJudger::JudgeReply>> AsyncJudge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WJudger::JudgeReply>>(AsyncJudgeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WJudger::JudgeReply>> PrepareAsyncJudge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::WJudger::JudgeReply>>(PrepareAsyncJudgeRaw(context, request, cq));
    }
    virtual ::grpc::Status Simple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::WJudger::SimpleReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WJudger::SimpleReply>> AsyncSimple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WJudger::SimpleReply>>(AsyncSimpleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WJudger::SimpleReply>> PrepareAsyncSimple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::WJudger::SimpleReply>>(PrepareAsyncSimpleRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Judge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs* request, ::grpc::ClientReadReactor< ::WJudger::JudgeReply>* reactor) = 0;
      virtual void Simple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs* request, ::WJudger::SimpleReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Simple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs* request, ::WJudger::SimpleReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::WJudger::JudgeReply>* JudgeRaw(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::WJudger::JudgeReply>* AsyncJudgeRaw(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::WJudger::JudgeReply>* PrepareAsyncJudgeRaw(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WJudger::SimpleReply>* AsyncSimpleRaw(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::WJudger::SimpleReply>* PrepareAsyncSimpleRaw(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::WJudger::JudgeReply>> Judge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::WJudger::JudgeReply>>(JudgeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::WJudger::JudgeReply>> AsyncJudge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::WJudger::JudgeReply>>(AsyncJudgeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::WJudger::JudgeReply>> PrepareAsyncJudge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::WJudger::JudgeReply>>(PrepareAsyncJudgeRaw(context, request, cq));
    }
    ::grpc::Status Simple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::WJudger::SimpleReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WJudger::SimpleReply>> AsyncSimple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WJudger::SimpleReply>>(AsyncSimpleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WJudger::SimpleReply>> PrepareAsyncSimple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::WJudger::SimpleReply>>(PrepareAsyncSimpleRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Judge(::grpc::ClientContext* context, const ::WJudger::JudgeArgs* request, ::grpc::ClientReadReactor< ::WJudger::JudgeReply>* reactor) override;
      void Simple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs* request, ::WJudger::SimpleReply* response, std::function<void(::grpc::Status)>) override;
      void Simple(::grpc::ClientContext* context, const ::WJudger::SimpleArgs* request, ::WJudger::SimpleReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::WJudger::JudgeReply>* JudgeRaw(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request) override;
    ::grpc::ClientAsyncReader< ::WJudger::JudgeReply>* AsyncJudgeRaw(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::WJudger::JudgeReply>* PrepareAsyncJudgeRaw(::grpc::ClientContext* context, const ::WJudger::JudgeArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WJudger::SimpleReply>* AsyncSimpleRaw(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::WJudger::SimpleReply>* PrepareAsyncSimpleRaw(::grpc::ClientContext* context, const ::WJudger::SimpleArgs& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Judge_;
    const ::grpc::internal::RpcMethod rpcmethod_Simple_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Judge(::grpc::ServerContext* context, const ::WJudger::JudgeArgs* request, ::grpc::ServerWriter< ::WJudger::JudgeReply>* writer);
    virtual ::grpc::Status Simple(::grpc::ServerContext* context, const ::WJudger::SimpleArgs* request, ::WJudger::SimpleReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Judge() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::WJudger::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::WJudger::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudge(::grpc::ServerContext* context, ::WJudger::JudgeArgs* request, ::grpc::ServerAsyncWriter< ::WJudger::JudgeReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Simple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Simple() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Simple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Simple(::grpc::ServerContext* /*context*/, const ::WJudger::SimpleArgs* /*request*/, ::WJudger::SimpleReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSimple(::grpc::ServerContext* context, ::WJudger::SimpleArgs* request, ::grpc::ServerAsyncResponseWriter< ::WJudger::SimpleReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Judge<WithAsyncMethod_Simple<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Judge() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::WJudger::JudgeArgs, ::WJudger::JudgeReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WJudger::JudgeArgs* request) { return this->Judge(context, request); }));
    }
    ~WithCallbackMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::WJudger::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::WJudger::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::WJudger::JudgeReply>* Judge(
      ::grpc::CallbackServerContext* /*context*/, const ::WJudger::JudgeArgs* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Simple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Simple() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::WJudger::SimpleArgs, ::WJudger::SimpleReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::WJudger::SimpleArgs* request, ::WJudger::SimpleReply* response) { return this->Simple(context, request, response); }));}
    void SetMessageAllocatorFor_Simple(
        ::grpc::MessageAllocator< ::WJudger::SimpleArgs, ::WJudger::SimpleReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::WJudger::SimpleArgs, ::WJudger::SimpleReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Simple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Simple(::grpc::ServerContext* /*context*/, const ::WJudger::SimpleArgs* /*request*/, ::WJudger::SimpleReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Simple(
      ::grpc::CallbackServerContext* /*context*/, const ::WJudger::SimpleArgs* /*request*/, ::WJudger::SimpleReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Judge<WithCallbackMethod_Simple<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Judge() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::WJudger::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::WJudger::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Simple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Simple() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Simple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Simple(::grpc::ServerContext* /*context*/, const ::WJudger::SimpleArgs* /*request*/, ::WJudger::SimpleReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Judge() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::WJudger::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::WJudger::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudge(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Simple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Simple() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Simple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Simple(::grpc::ServerContext* /*context*/, const ::WJudger::SimpleArgs* /*request*/, ::WJudger::SimpleReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSimple(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Judge() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Judge(context, request); }));
    }
    ~WithRawCallbackMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::WJudger::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::WJudger::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Judge(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Simple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Simple() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Simple(context, request, response); }));
    }
    ~WithRawCallbackMethod_Simple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Simple(::grpc::ServerContext* /*context*/, const ::WJudger::SimpleArgs* /*request*/, ::WJudger::SimpleReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Simple(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Simple : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Simple() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::WJudger::SimpleArgs, ::WJudger::SimpleReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::WJudger::SimpleArgs, ::WJudger::SimpleReply>* streamer) {
                       return this->StreamedSimple(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Simple() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Simple(::grpc::ServerContext* /*context*/, const ::WJudger::SimpleArgs* /*request*/, ::WJudger::SimpleReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSimple(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::WJudger::SimpleArgs,::WJudger::SimpleReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Simple<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Judge() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::WJudger::JudgeArgs, ::WJudger::JudgeReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::WJudger::JudgeArgs, ::WJudger::JudgeReply>* streamer) {
                       return this->StreamedJudge(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::WJudger::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::WJudger::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedJudge(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::WJudger::JudgeArgs,::WJudger::JudgeReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Judge<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Judge<WithStreamedUnaryMethod_Simple<Service > > StreamedService;
};

}  // namespace WJudger


#endif  // GRPC_wjudger_2eproto__INCLUDED
