// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: wjudger.proto
#ifndef GRPC_wjudger_2eproto__INCLUDED
#define GRPC_wjudger_2eproto__INCLUDED

#include "wjudger.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class WJudger final {
 public:
  static constexpr char const* service_full_name() {
    return "WJudger";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::JudgeReply>> Judge(::grpc::ClientContext* context, const ::JudgeArgs& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::JudgeReply>>(JudgeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::JudgeReply>> AsyncJudge(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::JudgeReply>>(AsyncJudgeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::JudgeReply>> PrepareAsyncJudge(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::JudgeReply>>(PrepareAsyncJudgeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Judge(::grpc::ClientContext* context, const ::JudgeArgs* request, ::grpc::ClientReadReactor< ::JudgeReply>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::JudgeReply>* JudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::JudgeReply>* AsyncJudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::JudgeReply>* PrepareAsyncJudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::JudgeReply>> Judge(::grpc::ClientContext* context, const ::JudgeArgs& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::JudgeReply>>(JudgeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::JudgeReply>> AsyncJudge(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::JudgeReply>>(AsyncJudgeRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::JudgeReply>> PrepareAsyncJudge(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::JudgeReply>>(PrepareAsyncJudgeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Judge(::grpc::ClientContext* context, const ::JudgeArgs* request, ::grpc::ClientReadReactor< ::JudgeReply>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::JudgeReply>* JudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request) override;
    ::grpc::ClientAsyncReader< ::JudgeReply>* AsyncJudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::JudgeReply>* PrepareAsyncJudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Judge_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Judge(::grpc::ServerContext* context, const ::JudgeArgs* request, ::grpc::ServerWriter< ::JudgeReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Judge() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudge(::grpc::ServerContext* context, ::JudgeArgs* request, ::grpc::ServerAsyncWriter< ::JudgeReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Judge<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Judge() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::JudgeArgs, ::JudgeReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::JudgeArgs* request) { return this->Judge(context, request); }));
    }
    ~WithCallbackMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::JudgeReply>* Judge(
      ::grpc::CallbackServerContext* /*context*/, const ::JudgeArgs* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Judge<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Judge() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Judge() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJudge(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Judge() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Judge(context, request); }));
    }
    ~WithRawCallbackMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Judge(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Judge : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Judge() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::JudgeArgs, ::JudgeReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::JudgeArgs, ::JudgeReply>* streamer) {
                       return this->StreamedJudge(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Judge() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Judge(::grpc::ServerContext* /*context*/, const ::JudgeArgs* /*request*/, ::grpc::ServerWriter< ::JudgeReply>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedJudge(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::JudgeArgs,::JudgeReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Judge<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_Judge<Service > StreamedService;
};


#endif  // GRPC_wjudger_2eproto__INCLUDED
