// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: wjudger.proto

#include "wjudger.pb.h"
#include "wjudger.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* WJudger_method_names[] = {
  "/WJudger/Judge",
};

std::unique_ptr< WJudger::Stub> WJudger::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WJudger::Stub> stub(new WJudger::Stub(channel, options));
  return stub;
}

WJudger::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Judge_(WJudger_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::JudgeReply>* WJudger::Stub::JudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request) {
  return ::grpc::internal::ClientReaderFactory< ::JudgeReply>::Create(channel_.get(), rpcmethod_Judge_, context, request);
}

void WJudger::Stub::async::Judge(::grpc::ClientContext* context, const ::JudgeArgs* request, ::grpc::ClientReadReactor< ::JudgeReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::JudgeReply>::Create(stub_->channel_.get(), stub_->rpcmethod_Judge_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::JudgeReply>* WJudger::Stub::AsyncJudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::JudgeReply>::Create(channel_.get(), cq, rpcmethod_Judge_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::JudgeReply>* WJudger::Stub::PrepareAsyncJudgeRaw(::grpc::ClientContext* context, const ::JudgeArgs& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::JudgeReply>::Create(channel_.get(), cq, rpcmethod_Judge_, context, request, false, nullptr);
}

WJudger::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WJudger_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< WJudger::Service, ::JudgeArgs, ::JudgeReply>(
          [](WJudger::Service* service,
             ::grpc::ServerContext* ctx,
             const ::JudgeArgs* req,
             ::grpc::ServerWriter<::JudgeReply>* writer) {
               return service->Judge(ctx, req, writer);
             }, this)));
}

WJudger::Service::~Service() {
}

::grpc::Status WJudger::Service::Judge(::grpc::ServerContext* context, const ::JudgeArgs* request, ::grpc::ServerWriter< ::JudgeReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


